### ISSUE TITLE
dev-02 services

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#1]
Implement minimal services.

**Comment by guillep** [comment]
What do you mean by minimal services? Some concrete implementations or the support for services?

**Comment by sbragagnolo** [comment]
Setup, and teardown default. With a block service implementation. Something like serve:[: service|] onServiceFinalization:[:service |] onError: [:err]. Not sure about the error, since we have he handlers. But something like that will be compatible with the old version

**Comment by guillep** [comment]
Tests added in 4c8303a1ff6a1ec2c5736dc727b33be705e918d8, missing documentation

**Comment by guillep** [comment]
Services implemented and tested.
