### ISSUE TITLE
Document Process Dashboard

### ISSUE THREAD

**Issue by guillep** [sbragagnolo/taskit#10]

**Comment by sbragagnolo** [comment]
Maldicion :P

**Comment by guillep** [comment]
What would be a milestone for this?

**Comment by sbragagnolo** [comment]
Basic daashboard doc.

**Comment by sbragagnolo** [comment]
This milestone. Im going to eat. If you want to merge master, go ahead :)

**Comment by guillep** [comment]
Can you check the changes log and add some points on the process dashboard?

-------- Original Message --------
