### ISSUE TITLE
We should change the repository's title

### ISSUE THREAD

**Issue by guillep** [sbragagnolo/taskit#14]
Not it reads:

>TaskIT 2.0 sandbox. This repo is a sandbox to implement some features and changes for taskit new version

We should change it by something like (I copy paste from the readme):

> TaskIt is a library that ease Process usage in Pharo. It provides abstractions to execute and synchronize concurrent tasks, and several pre-built mechanisms that are useful for many application developers.

Or something shorter:

> A concurrent task management library for [Pharo](www.pharo.org)

In any case, I do not have access to change it myself :)

**Comment by sbragagnolo** [comment]
done

**Comment by sbragagnolo** [comment]
do you know how to give admin rights here?

**Comment by guillep** [comment]
Nope. My friend, the owner you are :stuck_out_tongue_closed_eyes:
