### ISSUE TITLE
Make work the process dashboard in dev02

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#2]
MAny things have change in dev02, ensure dashboard and old tests

**Comment by sbragagnolo** [comment]
I merged dev-0.2-tktprocess with dev-0.2. Runned all tests with TKTPharoProcess provider and TKTTaskItProcessProvider. all in green :)

**Comment by sbragagnolo** [comment]
Now, this issue will open new issues. cause of the changes done for this version for the TKTProcess and the browser.

**Comment by guillep** [comment]
New issues?

**Comment by sbragagnolo** [comment]
Yeah, we will discuss next week. In any case is for next version. No rush on this
