### ISSUE TITLE
TKTService recursive approach probably leads to infinite context chains

### ISSUE THREAD

**Issue by dionisiydk** [sbragagnolo/taskit#26]
Recursion is defined here:
```Smalltalk
 TKTService>>scheduleRecursiveTask
	stopRequested
		ifTrue: [ worker schedule: [ self doStop ] ]
		ifFalse: [
			worker schedule: [ 
				self stepService.
				self scheduleRecursiveTask ]]
```
While #schedule: message not immediately evaluates given block it will still instantiate block closure with outer context reference. It means that every service step will produce extra context reference up to first "stepService" block. And if service is constantly lived task then at some point memory will ends.

**Comment by dionisiydk** [comment]
Possible fix is to represent this blocks as concrete TKTTask instances

**Comment by sbragagnolo** [comment]
Sorry for the long long long delay :D . we are using a sameblock policy. :)

**Comment by sbragagnolo** [comment]
Sorry for the long long long delay :D . we are using a sameblock policy. :)
