### ISSUE TITLE
Taskit Process Dashboard not work in Pharo 6

### ISSUE THREAD

**Issue by fedemennite** [sbragagnolo/taskit#28]
Hi,
the process dashboard needs some slight changes to work in Pharo 6:
- TKTFastTableProcess>#manager change the reference to TabManager to TabManagerMorph
- TKTFastTableProcess>#taskItProcessesTable change the reference to Tab to TabMorph
- TKTFastTableProcess>#systemProcessesTable change the reference to Tab to TabMorph
Best Regards,
Federico

**Comment by sbragagnolo** [comment]
This is working properly
