### ISSUE TITLE
the future method on block is not working

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#29]
There is a missing class

**Comment by guillep** [comment]
Do you mean this:

```smalltak
[ bla ] future.
```

?

**Comment by sbragagnolo** [comment]
yep. It does not work with the default Baseline. There is something wrong in the configuration,

**Comment by sbragagnolo** [comment]
Fixed.
The reason was that the TaskITDebugger package was not well defined. (Some extensions were commited into the core)
