### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#3]
Check that it's working over this repository. Adapt the scripts to scale.

**Comment by guillep** [comment]
Or travis?

**Comment by sbragagnolo** [comment]
What ever you want. I put jenkins because of INRIA.  I never used travis. Can you point me any travis conf for copying?

**Comment by guillep** [comment]
https://github.com/guillep/Matra/blob/master/.travis.yml

**Comment by sbragagnolo** [comment]
Beautiful :) 👍  Im doing it in a couple of hours!

**Comment by sbragagnolo** [comment]
Travis done! Im waiting to see the test report. 
I added the building image into the README.me, since it's markdown. 

https://travis-ci.org/sbragagnolo/taskit/

**Comment by guillep** [comment]
Tests are running!
