### ISSUE TITLE
Error management | Futures

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#31]
The futures are exploding and spawning a debugger as soon are they deploy an error. This leads to many problems, like the inhability of analysing sets of errors as dead errors, the spawning of massive amounts of debuggers, etc. 

For this I propose to change the behaviour of the debugging extention for spawning the Debugger when the future value is used as a value.

**Comment by guillep** [comment]
Don't get this. Do you have a code example?

**Comment by sbragagnolo** [comment]
futures := contracts collect:[ : c | [ c doSomething ] future  ] .

**Comment by guillep** [comment]
Ahhh, did not know that. YES, otherwise it kills the purpose.

**Comment by sbragagnolo** [comment]
Done. There was an structural error
