### ISSUE TITLE
TKTService hang bug

### ISSUE THREAD

**Issue by daniel-sasu** [sbragagnolo/taskit#34]
While using this piece of code, found in the project [readme](https://github.com/reservoir-dogs-lille/taskit#creating-services-with-blocks), the virtual machine ceases to respond, while the cpu usage is at 100%.
 
```smalltalk
service := TKTParameterizableService new.
service name: 'Generic watcher service'.
service onSetUpDo: [ Transcript show: 'File watcher started' ].
service onTearDownDo: [ Transcript show: 'File watcher finished' ].
service step: [
  'temp.txt' asFileReference exists
    ifFalse: [ Transcript show: 'file does not exist!' ] ].

service start.
```

The first solution we found is adding a time delay :
```smalltalk
service := TKTParameterizableService new.
service name: 'Generic watcher service'.
service onSetUpDo: [ 'File watcher started' logCr ].
service onTearDownDo: [ 'File watcher finished' logCr].
service step: [ 2 seconds wait.
  'temp.txt' asFileReference exists
    ifFalse: [ 'file does not exist!' logCr] ].

service start.
```

This problem may be solved by changing the default time delay for the service or adding a 
mechanism for setting a time delay, via the constructor or a setter.

**Comment by sbragagnolo** [comment]
Hi Daniel! 

Thanks for the issue, sorry I did not respond faster.
 Exactly as you say, the service needs to define an amount of time to wait on it, without that timing it would consume all the processing time. 

I think as well to have a default delay time would be a good idea, and execute it on the library side. 
If you want to  push a change with it, you are more than welcome. If not I will do it this week.
Thanks again!

**Comment by daniel-sasu** [comment]
Hi !
Me and my classmates we will do it this week.
Thank you

**Comment by sbragagnolo** [comment]
Great! Let me know if you have any issue on this.
