### ISSUE TITLE
Worker pool exceeds size

### ISSUE THREAD

**Issue by daniel-sasu** [sbragagnolo/taskit#36]
While executing this test, seldom it gives a positive result
(The conditions are met to create the failure):

```smalltalk
TKTCommonQueueWorkerPoolTests >>> testWorkerPoolDoesNotExceedPoolSizeWhenSchedulingTasksInParallel
	<expectedFailure>
	| pool totalTasks futures |
	pool := TKTCommonQueueWorkerPool new.
	pool poolMaxSize: 10.
	pool start.
	totalTasks := 0.
	futures := AtomicSharedQueue new.
	1 to: 10 do: [ :i | futures nextPut: (pool future: [ 10 timesRepeat: [ futures nextPut: (pool future: [ totalTasks := totalTasks + 1 ]) ] ]) ].
	[ futures isEmpty ] whileFalse: [ futures next waitForCompletion: 100 milliSeconds ].
	self assert: totalTasks equals: 100.
	self assert: pool size equals: 10
```

![capture du 2018-03-16 16-32-32](https://user-images.githubusercontent.com/15184285/37529579-d49ba0f4-2937-11e8-8573-351cbc5c8b9d.png)

I think there might be an issue linked to the time delays.

**Comment by sbragagnolo** [comment]
Hi Daniel! 

Me my self i added that <expectedFailure> to finish the integration (since it was not a show stopper) 
I am working on making the addition of a new worker safe for mt.
