### ISSUE TITLE
Transcript do not show result

### ISSUE THREAD

**Issue by chicoary** [sbragagnolo/taskit#63]
The code below does not display the result in the Transcript.

```
aFuture: = [2 + 2] future.
aFuture onSuccessDo: [: result | result logCr ].
```

**Comment by sbragagnolo** [comment]
Pharo8 @ Windows cannot reproduce.

**Comment by sbragagnolo** [comment]
Could you please, give me more details, like installation, pharo version, step by step how did you treat your image before executing this code? thanks!
