### ISSUE TITLE
Release version 0.2

### ISSUE THREAD

**Issue by guillep** [sbragagnolo/taskit#9]
- [x] Should merge dev-0.2 into master
- [x] Create and push a changes log
- [x] Create new development branch (dev-0.3)
- [x] Update versions in readme from download section. It is important to do it before tagging 
- [x] git tag -a v0.2

Suggested changes log:

# TaskIt

https://github.com/sbragagnolo/taskit

TaskIt is a library that ease Process usage in Pharo. It provides abstractions to execute and synchronize concurrent tasks, and several pre-built mechanisms that are useful for many application developers. This chapter explores starts by familiarizing the reader with TaskIt's abstractions, guided by examples and code snippets. At the end, we discuss TaskIt extension points and possible customizations.

# ChangesLog TaskIt v0.2

## Major Features

- Task Runners
  - NewProcessTaskRunner
  - LocalProcessTaskRunner
  - Worker
  - WorkerPool
- Futures with callbacks
- Future combinators
- Future synchronous access
- Services

## Infrastructure

- Travis CI
	https://travis-ci.org/sbragagnolo/taskit
- Documentation
	https://github.com/sbragagnolo/taskit/blob/master/README.md

## Minor changes log (from commits)

- Enhanced class comments
- TKTWorker processes are terminated in case the worker is collected. See Issues #8 and #5
- Process Dashboard. 
        - Adds TKTTaskItProcessProvider by default with the extension package 
        - Hides job and task fields since there are not reachable any more.

**Comment by sbragagnolo** [comment]
Issue #9

**Comment by sbragagnolo** [comment]
Updated changelog.

**Comment by sbragagnolo** [comment]
eeeeee. beer next week :).
